[package]
name = "transformer"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
iref = "3.2.2"
iref-enum = "3.0.0"
sophia = { version = "0.9.0", features = ["sparql"] }
static-iref = "3.0.0"
thiserror = "2.0.16"
tracing = "0.1.44"
